[[redirects]]
  from = "http://pensive-stonebraker-5ee769.netlify.com/*"
  to = "http://visualtokyo.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://pensive-stonebraker-5ee769.netlify.com/*"
  to = "https://visualtokyo.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
